/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controlador.ControladorObraSocial;
import controlador.ControladorTipoCuota;
import javax.swing.JOptionPane;
import modelo.ObraSocial;
import modelo.TipoCuota;
import utilidades.Mensaje;

/**
 *
 * @author COCO
 */
public class FormularioTipoCuota extends javax.swing.JDialog {

    int tipo;
    
    TipoCuota tipoCuota;
    int id;
    
    /**
     * Creates new form FormularioObraSocial
     */
    public FormularioTipoCuota(int tipo) {
        initComponents();
        this.tipo = tipo;
        if(tipo == 0)
            jLabelTitulo.setText("Nuevo tipo de cuota");
        else jLabelTitulo.setText("Editando tipo de cuota");
        setModal(true);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void setData(int id){
        
        this.id = id;
        tipoCuota = new TipoCuota();
        tipoCuota.setIdCuota(id);
        ControladorTipoCuota.getDatos(tipoCuota);
        
        jTextField1.setText(tipoCuota.getNombre());
        jSpinner1.getModel().setValue(tipoCuota.getImporte());
        jTextField2.setText(String.valueOf(tipoCuota.getFrecuencia()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevaObraSocialPanel = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nuevaObraSocialPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo.setText("Nueva Cuota");

        jLabel2.setText("Nombre:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Importe: ");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), null, Float.valueOf(0.1f)));

        jLabel6.setText("Frecuencia:");

        javax.swing.GroupLayout nuevaObraSocialPanelLayout = new javax.swing.GroupLayout(nuevaObraSocialPanel);
        nuevaObraSocialPanel.setLayout(nuevaObraSocialPanelLayout);
        nuevaObraSocialPanelLayout.setHorizontalGroup(
            nuevaObraSocialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevaObraSocialPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(nuevaObraSocialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevaObraSocialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jSpinner1)
                    .addComponent(jTextField2))
                .addContainerGap())
            .addGroup(nuevaObraSocialPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(nuevaObraSocialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addGap(105, 105, 105))
        );
        nuevaObraSocialPanelLayout.setVerticalGroup(
            nuevaObraSocialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevaObraSocialPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(nuevaObraSocialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevaObraSocialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevaObraSocialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nuevaObraSocialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevaObraSocialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tipo == 0){ //Nuevo
            
            tipoCuota = new TipoCuota();
            tipoCuota.setNombre(jTextField1.getText());
            tipoCuota.setImporte((float)jSpinner1.getModel().getValue());
            tipoCuota.setFrecuencia(Integer.parseInt(jTextField2.getText()));
            //Tomo valores de campos y se los asigno al objeto
            String resultado = ControladorTipoCuota.insertar(tipoCuota);
            if(resultado.equals(""))  //No hubo error
                Mensaje.mostrarMensaje(rootPane, "Tipo de cuota agregada con éxito", "Enhorabuena", JOptionPane.INFORMATION_MESSAGE);
            else Mensaje.mostrarMensaje(rootPane, "Error al agregar tipo de cuota:\n" + resultado, "Error", JOptionPane.ERROR_MESSAGE);
            
            dispose();
            
        }
        else {
        
            tipoCuota.setNombre(jTextField1.getText());
            tipoCuota.setImporte((float)jSpinner1.getModel().getValue());
            tipoCuota.setFrecuencia(Integer.parseInt(jTextField2.getText()));
            String resultado = ControladorTipoCuota.editar(tipoCuota);
            if(resultado.equals(""))  //No hubo error
                Mensaje.mostrarMensaje(rootPane, "Tipo de cuota editada con éxito", "Enhorabuena", JOptionPane.INFORMATION_MESSAGE);
            else Mensaje.mostrarMensaje(rootPane, "Error al editar tipo de cuota:\n" + resultado, "Error", JOptionPane.ERROR_MESSAGE);
            
            dispose();
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel nuevaObraSocialPanel;
    // End of variables declaration//GEN-END:variables
}
