/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import controlador.ControladorCuentaCorriente;
import controlador.ControladorFactura;
import controlador.ControladorRecibo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import modelo.ConceptoCuentaCorriente;
import utilidades.Fecha;
import utilidades.Formato;
import utilidades.Mensaje;

/**
 *
 * @author COCO
 */
public class GenerarFactura extends javax.swing.JDialog {

    ArrayList<ConceptoCuentaCorriente> conceptos;
    
    private DefaultTableModel modelo = new DefaultTableModel();
    private DefaultTableColumnModel modeloColumnas = new DefaultTableColumnModel();
    
    int matricula;
    
    /**
     * Creates new form CobrarDebitos
     * @param matricula
     */
    public GenerarFactura(int matricula) {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.matricula = matricula;
        
        conceptos = new ArrayList<>();
        
        modelo = (DefaultTableModel) jTable1.getModel();
        modeloColumnas = (DefaultTableColumnModel) jTable1.getColumnModel();
        
        llenarTodo();
        
        fechatxt.setText(Fecha.getFechaActual());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        montotxt = new javax.swing.JTextField();
        facturartxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fechatxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Detalle", "Importe", "Facturar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        montotxt.setText("0.0");
        montotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montotxtActionPerformed(evt);
            }
        });

        facturartxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                facturartxtFocusLost(evt);
            }
        });

        jLabel1.setText("Monto total");

        jLabel2.setText("Nro factura");

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha factura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(montotxt)
                                    .addComponent(facturartxt))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facturartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        float saldo = 0;
        int i = 0;
        for(ConceptoCuentaCorriente concepto : conceptos){
            if((Boolean)modelo.getValueAt(i, 3))
                saldo += concepto.getImporte();
            i++;
        }
        
        montotxt.setText(String.valueOf(saldo));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String factura = facturartxt.getText();
        if(!factura.equals("")){
        
            if(factura.contains("-")){
                
                ArrayList<ConceptoCuentaCorriente> nuevos = new ArrayList<>();
                int i = 0;
                for(ConceptoCuentaCorriente concepto : conceptos){
                    if((Boolean)modelo.getValueAt(i, 3))
                        nuevos.add(concepto);
                    i++;
                }
                facturartxt.setText(Formato.darFormatoFactura(factura));
                if(!montotxt.getText().equals("0.0")){
                    String resultado = ControladorFactura.generarFactura(nuevos, Float.parseFloat(montotxt.getText()), matricula, facturartxt.getText(), Fecha.invertirFecha(fechatxt.getText()));
                    if(resultado.equals("")){  //No hubo error
                        Mensaje.mostrarMensaje(rootPane, "Facturas generadas con exito", "Enhorabuena", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    }
                    else Mensaje.mostrarMensaje(rootPane, "Error al cobrar los debitos:\n" + resultado, "Error", JOptionPane.ERROR_MESSAGE);
                }
                else Mensaje.mostrarMensaje(rootPane, "Error monto incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            
            }
            else Mensaje.mostrarMensaje(rootPane, "Formato de nro de factura invalido", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        else Mensaje.mostrarMensaje(rootPane, "Ingrese un numero de factura", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void montotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montotxtActionPerformed

    private void facturartxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_facturartxtFocusLost
        String s = facturartxt.getText();
        if(s.contains("-"))
            facturartxt.setText(Formato.darFormatoFactura(s));
        else Mensaje.mostrarMensaje(rootPane, "Formato incorrecto de nro de factura", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_facturartxtFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField facturartxt;
    private javax.swing.JTextField fechatxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField montotxt;
    // End of variables declaration//GEN-END:variables

    private void llenarTodo() {
        
        for(int i = jTable1.getRowCount() - 1; i >= 0; i--){
        
            modelo.removeRow(i);
        
        }
        
        conceptos.clear();
        
        ControladorCuentaCorriente.obtenerCuotasSinFactura(conceptos, matricula);
        
        for(ConceptoCuentaCorriente concepto : conceptos){
        
            Object[] data = { Fecha.invertirFecha(concepto.getFecha()), concepto.getDetalle(), concepto.getImporte(), false };
            modelo.addRow(data);
            
        }
        
    }
}
