/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import controlador.ControladorObraSocial;
import controlador.ControladorProfesional;
import controlador.ControladorTipoCuota;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.DetalleLiquidacion;
import modelo.Liquidacion;
import modelo.ObraSocial;
import modelo.Profesional;
import modelo.TipoCuota;

/**
 *
 * @author Viic
 */
public class TablaLiquidacion extends javax.swing.JDialog {

   // private DefaultTableModel modeloTablaLiquidacion = new DefaultTableModel();
   // private DefaultTableColumnModel modeloColumnasLiquidacion = new DefaultTableColumnModel();
    @SuppressWarnings("UseOfObsoleteCollectionType")
    Vector<String> nombresColumnas = new Vector();
    private ArrayList<TipoCuota> tipoCuotas;
    private ArrayList<DetalleLiquidacion> detalles;
    JTable tablaLiquidacion;
    
    /**
     * Creates new form Liquidacion
     */
    public TablaLiquidacion(Liquidacion liquidacion) {
        this.tablaLiquidacion = new JTable();
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        setResizable(false);
        
        // Lleno los labels con los datos de la liquidación
        ObraSocial obrasocial = null;
        obrasocial.setIdObraSocial(liquidacion.getIdObraSocial());
        ControladorObraSocial.getDatos(obrasocial);
        this.nombreObraSocial.setText(obrasocial.getNombre());
        
        this.importe.setText(liquidacion.getImporte());
        
        this.fechaPago.setText(liquidacion.getFechaPago());
        
        this.fechaRecibida.setText(liquidacion.getFechaRecibida());
        
        // Armo la tabla y la agrego en el ScrollPane
        llenarNombresColumnas(nombresColumnas);
        DefaultTableModel modeloTabla = new DefaultTableModel(nombresColumnas,0);
   
        tablaLiquidacion.setModel(modeloTabla);
        tablaLiquidacion.setEnabled(false);
        this.tablaScrollPane.add(tablaLiquidacion);
        
        //Lleno la tabla con el detalle de la liquidacion
        detalles = liquidacion.getDetalles();
        llenarTodo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Exportar = new javax.swing.JButton();
        Imprimir = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        importe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaRecibida = new javax.swing.JLabel();
        fechaPago = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tablaScrollPane = new javax.swing.JScrollPane();
        nombreObraSocial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo.setText("Liquidación Obra Social:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exportar.png"))); // NOI18N
        Exportar.setText("Exportar");
        Exportar.setFocusable(false);
        Exportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Exportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarActionPerformed(evt);
            }
        });

        Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir.png"))); // NOI18N
        Imprimir.setText("Imprimir");
        Imprimir.setFocusable(false);
        Imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Imprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setFocusable(false);
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Importe Liquidado: $");

        importe.setText("importe");

        jLabel4.setText("Fecha Recibida:");

        fechaRecibida.setText("fecha");

        fechaPago.setText("fecha");

        jLabel7.setText("Fecha Pago:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaRecibida)
                .addGap(119, 119, 119)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaPago)
                .addGap(164, 164, 164)
                .addComponent(Imprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Exportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Eliminar, Exportar, Imprimir});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exportar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Imprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(importe)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(fechaPago))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(fechaRecibida)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Eliminar, Exportar, Imprimir});

        nombreObraSocial.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nombreObraSocial.setText("nombre Obra Social");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablaScrollPane))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreObraSocial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(nombreObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarActionPerformed
        // TODO add your handling code here:
        ListadoLiquidaciones form = new ListadoLiquidaciones();
        form.setVisible(true);
    }//GEN-LAST:event_ExportarActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        ListadoTipoCuotas form = new ListadoTipoCuotas();
        form.setVisible(true);
    }//GEN-LAST:event_ImprimirActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        ListadoMateriales form = new ListadoMateriales();
        form.setVisible(true);
    }//GEN-LAST:event_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Exportar;
    private javax.swing.JButton Imprimir;
    private javax.swing.JLabel fechaPago;
    private javax.swing.JLabel fechaRecibida;
    private javax.swing.JLabel importe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombreObraSocial;
    private javax.swing.JScrollPane tablaScrollPane;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Llena el vector con el que se creara el modelo de la tabla de liquidación
     * agrega las columnas definidas por defecto (Apellido y nombre, matricula, etc)
     * y agrega una colimna por cada nombre de cuota distinto
     * 
     * @param columnas 
     */
    private void llenarNombresColumnas(Vector<String> columnas) {
        
        // Agrega columnas predefinidas
        columnas.add("Apellido y Nombre");
        columnas.add("Matricula");
        columnas.add("Importe Bruto");
        columnas.add("10%"); //Esto va como cuota Esporadica?
        
        // Agregar una columna por cada cuota existente
        tipoCuotas = new ArrayList<>();
        ControladorTipoCuota.getTipos(tipoCuotas);
        String nombreTipo = "";
        for(TipoCuota tipo : tipoCuotas){
            nombreTipo = tipo.getNombre();
            if (!columnas.contains(nombreTipo)){ 
            //Para evitar columnas con igual nombre, por ejemplo el caso transmec
                columnas.add(nombreTipo);
            }
        }
        
        
        columnas.add("Neto a Pagar");
        
      //  modeloColumnasLiquidacion.addColumn(null);
    }

    /**
     * Llena la tabla de la liquidación recorriendo los detalles de la misma
     * y recorriendo los conceptos de cada detalle.
     */
    private void llenarTodo() {
        
        DefaultTableModel modelo = (DefaultTableModel) tablaLiquidacion.getModel();
        for(int i = tablaLiquidacion.getRowCount() - 1; i >= 0; i--){
        
            modelo.removeRow(i);
        
        }
       
        for(DetalleLiquidacion detalle : detalles){
            Profesional profesional = new Profesional();
            profesional.setMatricula(detalle.getMatricula());
            ControladorProfesional.getDatos(profesional);
            String[] data = { String.valueOf(detalle.getMatricula()), profesional.getNombre(), String.valueOf(detalle.getAtributo()), String.valueOf(detalle.getAtributo()*0.10) };
            modelo.addRow(data);
        
        }
        
        //nombresColumnas.add("");
        
    }
}
